### ISSUE TITLE
No setup.py in the project

### ISSUE THREAD

**Issue by cfir** [madman-bob/python-argparse-utils#1]

**Comment by madman-bob** [comment]
https://github.com/madman-bob/python-argparse-utils/blob/master/pypi_upload/setup.py

**Comment by somini** [comment]
Can you include something on the source file uploaded to PyPI? I'm trying to package this on AUR, and had to adapt that to build from the PyPI source:

- `requirements.txt` is needed, but not included on the source tarball. But it's empty now, so I ignored it
- The whole business with `CIRCLE_TAG` should not be used

Here's the package: https://aur.archlinux.org/packages/python-argparse-utils/

`setup.py` here: https://aur.archlinux.org/cgit/aur.git/tree/setup.py?h=python-argparse-utils

**Comment by somini** [comment]
In addition, the published wheel on PyPI depends on twine. This means a simple `pip install --user argparse-utils` pulls `twine`, that requires a C compiler and it's a general hassle.
This is a very simple pure Python package.

**Comment by somini** [comment]
> In addition, the published wheel on PyPI depends on twine.

This was surprising to me since the requirements don't do this. This is done here:

https://github.com/madman-bob/python-argparse-utils/blob/master/.circleci/config.yml#L63
